#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OrderNowAndroid.Resource", IsApplication=true)]

namespace OrderNowAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_down_exit = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int card_types = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010020
			public const int auxiliary_view_position = 2130772000;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010017
			public const int confirm_logout = 2130771991;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f010011
			public const int done_button_background = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int done_button_text = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int extra_fields = 2130771980;
			
			// aapt resource value: 0x7f010018
			public const int fetch_user_info = 2130771992;
			
			// aapt resource value: 0x7f01001d
			public const int foreground_color = 2130771997;
			
			// aapt resource value: 0x7f010021
			public const int horizontal_alignment = 2130772001;
			
			// aapt resource value: 0x7f01001c
			public const int is_cropped = 2130771996;
			
			// aapt resource value: 0x7f010019
			public const int login_text = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int logout_text = 2130771994;
			
			// aapt resource value: 0x7f010012
			public const int multi_select = 2130771986;
			
			// aapt resource value: 0x7f01001e
			public const int object_id = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int preset_size = 2130771995;
			
			// aapt resource value: 0x7f010013
			public const int radius_in_meters = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int results_limit = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int search_text = 2130771989;
			
			// aapt resource value: 0x7f01000b
			public const int show_pictures = 2130771979;
			
			// aapt resource value: 0x7f010016
			public const int show_search_box = 2130771990;
			
			// aapt resource value: 0x7f01000d
			public const int show_title_bar = 2130771981;
			
			// aapt resource value: 0x7f01001f
			public const int style = 2130771999;
			
			// aapt resource value: 0x7f010010
			public const int title_bar_background = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int title_text = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050011
			public const int blue_sds = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_blue = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_likeboxcountview_border_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_likeboxcountview_text_color = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_likebutton_text_color = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_likeview_text_color = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_loginview_text_color = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_picker_search_bar_background = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_picker_search_bar_text = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int tab_not_selected = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int tab_selected = 2131034128;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_likeboxcountview_border_radius = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int com_facebook_likeboxcountview_border_width = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_likeboxcountview_caret_height = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_likeboxcountview_caret_width = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int com_facebook_likeboxcountview_text_padding = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int com_facebook_likeboxcountview_text_size = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_likebutton_compound_drawable_padding = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_likebutton_padding_bottom = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_likebutton_padding_left = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_likebutton_padding_right = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_likebutton_padding_top = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_likebutton_text_size = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_likeview_edge_padding = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_likeview_internal_padding = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_likeview_text_size = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_loginview_compound_drawable_padding = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_loginview_padding_bottom = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_loginview_padding_left = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_loginview_padding_right = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_loginview_padding_top = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_loginview_text_size = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_picker_divider_width = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_picker_place_image_size = 2131099651;
			
			// aapt resource value: 0x7f06001e
			public const int com_facebook_profilepictureview_preset_size_large = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int com_facebook_profilepictureview_preset_size_normal = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int com_facebook_profilepictureview_preset_size_small = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int com_facebook_tooltip_horizontal_padding = 2131099679;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alexanderKeithPint = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border_confirm = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int breakfast = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btnProfileMenuStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btnProfilePictureStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int budweiser2Liters = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ButtonSignInWFacebook = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ButtonSignUpStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int calamari = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ceasarSalad = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int centDrives = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int chesseBurger = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chickenWings = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_button_blue = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_button_blue_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_button_blue_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_blue_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_button_check = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_button_check_off = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_button_check_on = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_button_grey_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_button_grey_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_button_grey_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_button_like = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_button_like_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_button_like_background_selected = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_button_like_icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_button_like_icon_selected = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_button_like_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_button_like_selected = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_close = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_inverse_icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_list_divider = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_list_section_header_background = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_loginbutton_silver = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_logo = 2130837539;
			
			// aapt resource value: 0x7f02006f
			public const int com_facebook_picker_default_separator_color = 2130837615;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_picker_item_background = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_picker_list_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_picker_list_longpressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_picker_list_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int com_facebook_picker_list_selector = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_picker_list_selector_background_transition = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int com_facebook_picker_list_selector_disabled = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int com_facebook_picker_magnifier = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int com_facebook_picker_top_button = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int com_facebook_place_default_icon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int com_facebook_profile_default_icon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int com_facebook_profile_picture_blank_portrait = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int com_facebook_profile_picture_blank_square = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int com_facebook_tooltip_black_background = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int com_facebook_tooltip_black_bottomnub = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int com_facebook_tooltip_black_topnub = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int com_facebook_tooltip_black_xout = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int com_facebook_tooltip_blue_background = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int com_facebook_tooltip_blue_bottomnub = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int com_facebook_tooltip_blue_topnub = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int com_facebook_tooltip_blue_xout = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int com_facebook_top_background = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int com_facebook_top_button = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int creditCard = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int dinner = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int drinksnBeers = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int edit_text_style = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int events = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int eventsSelected = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int fries = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int hockeyBackground = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Icon = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int info = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int infoSelected = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int label = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int letter = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int malibuRed = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int menu = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int menuSelected = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int mojito = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int moreOption = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int order = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int orderNow = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int orderNowPressed = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int orderSelected = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int pepperoniPizza = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int phone = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int profile = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int profilePictureEdit = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int profileSelected = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int RickardsRed4L = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int roundCorners = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int sdsBackground = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int sdsBanner = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int sdsLogo = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int sdsNachos = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int sdsSignInBackground = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int selected_state = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int selectorActionBar = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int selectorBtnOrderNow = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int selectorCancelStyle = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int selectorConfirmStyle = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int selectorEventsTab = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int selectorInfosTab = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int selectorMenuTab = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int selectorOrderTab = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int selectorProfileTab = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int selectorTextView = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int slapshot500ml = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int spaghettiBolognese = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int specialsPromotions = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int splashScreen = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int steak = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int Warning = 2130837614;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0006
			public const int bottom = 2131361798;
			
			// aapt resource value: 0x7f0a0003
			public const int box_count = 2131361795;
			
			// aapt resource value: 0x7f0a003a
			public const int btnCancelOrderNow = 2131361850;
			
			// aapt resource value: 0x7f0a0039
			public const int btnConfirmOrderNow = 2131361849;
			
			// aapt resource value: 0x7f0a003d
			public const int btnDialogEmail = 2131361853;
			
			// aapt resource value: 0x7f0a0074
			public const int btnNextSignUp = 2131361908;
			
			// aapt resource value: 0x7f0a0050
			public const int btnSectionBreakfast = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int btnSectionDinner = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int btnSectionDrinks = 2131361874;
			
			// aapt resource value: 0x7f0a004f
			public const int btnSectionPromotions = 2131361871;
			
			// aapt resource value: 0x7f0a0065
			public const int btnSignIn = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int btnSignInWFacebook = 2131361894;
			
			// aapt resource value: 0x7f0a0070
			public const int btnSignUp = 2131361904;
			
			// aapt resource value: 0x7f0a0004
			public const int button = 2131361796;
			
			// aapt resource value: 0x7f0a005b
			public const int button1 = 2131361883;
			
			// aapt resource value: 0x7f0a005d
			public const int button2 = 2131361885;
			
			// aapt resource value: 0x7f0a005f
			public const int button3 = 2131361887;
			
			// aapt resource value: 0x7f0a0061
			public const int button4 = 2131361889;
			
			// aapt resource value: 0x7f0a0059
			public const int button5 = 2131361881;
			
			// aapt resource value: 0x7f0a003e
			public const int card_view = 2131361854;
			
			// aapt resource value: 0x7f0a0046
			public const int cbxStart = 2131361862;
			
			// aapt resource value: 0x7f0a0009
			public const int center = 2131361801;
			
			// aapt resource value: 0x7f0a0064
			public const int checkBox1 = 2131361892;
			
			// aapt resource value: 0x7f0a002d
			public const int com_facebook_body_frame = 2131361837;
			
			// aapt resource value: 0x7f0a002f
			public const int com_facebook_button_xout = 2131361839;
			
			// aapt resource value: 0x7f0a001d
			public const int com_facebook_login_activity_progress_bar = 2131361821;
			
			// aapt resource value: 0x7f0a001c
			public const int com_facebook_picker_activity_circle = 2131361820;
			
			// aapt resource value: 0x7f0a001f
			public const int com_facebook_picker_checkbox = 2131361823;
			
			// aapt resource value: 0x7f0a0023
			public const int com_facebook_picker_checkbox_stub = 2131361827;
			
			// aapt resource value: 0x7f0a0027
			public const int com_facebook_picker_divider = 2131361831;
			
			// aapt resource value: 0x7f0a0026
			public const int com_facebook_picker_done_button = 2131361830;
			
			// aapt resource value: 0x7f0a0020
			public const int com_facebook_picker_image = 2131361824;
			
			// aapt resource value: 0x7f0a0024
			public const int com_facebook_picker_list_section_header = 2131361828;
			
			// aapt resource value: 0x7f0a001b
			public const int com_facebook_picker_list_view = 2131361819;
			
			// aapt resource value: 0x7f0a0021
			public const int com_facebook_picker_profile_pic_stub = 2131361825;
			
			// aapt resource value: 0x7f0a001e
			public const int com_facebook_picker_row_activity_circle = 2131361822;
			
			// aapt resource value: 0x7f0a002c
			public const int com_facebook_picker_search_text = 2131361836;
			
			// aapt resource value: 0x7f0a0022
			public const int com_facebook_picker_title = 2131361826;
			
			// aapt resource value: 0x7f0a0029
			public const int com_facebook_picker_title_bar = 2131361833;
			
			// aapt resource value: 0x7f0a0028
			public const int com_facebook_picker_title_bar_stub = 2131361832;
			
			// aapt resource value: 0x7f0a0025
			public const int com_facebook_picker_top_bar = 2131361829;
			
			// aapt resource value: 0x7f0a002b
			public const int com_facebook_search_bar_view = 2131361835;
			
			// aapt resource value: 0x7f0a0031
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131361841;
			
			// aapt resource value: 0x7f0a0030
			public const int com_facebook_tooltip_bubble_view_text_body = 2131361840;
			
			// aapt resource value: 0x7f0a002e
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131361838;
			
			// aapt resource value: 0x7f0a0034
			public const int com_facebook_usersettingsfragment_login_button = 2131361844;
			
			// aapt resource value: 0x7f0a0032
			public const int com_facebook_usersettingsfragment_logo_image = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int com_facebook_usersettingsfragment_profile_name = 2131361843;
			
			// aapt resource value: 0x7f0a0035
			public const int dialog_sign_up_container = 2131361845;
			
			// aapt resource value: 0x7f0a0055
			public const int imageButton1 = 2131361877;
			
			// aapt resource value: 0x7f0a0043
			public const int imgBtnMoreOptions = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int imgBtnOrderNow = 2131361860;
			
			// aapt resource value: 0x7f0a003f
			public const int imgItem = 2131361855;
			
			// aapt resource value: 0x7f0a0058
			public const int imgPhone = 2131361880;
			
			// aapt resource value: 0x7f0a0007
			public const int inline = 2131361799;
			
			// aapt resource value: 0x7f0a0000
			public const int large = 2131361792;
			
			// aapt resource value: 0x7f0a0062
			public const int layoutAllergies = 2131361890;
			
			// aapt resource value: 0x7f0a0057
			public const int layoutBorder = 2131361879;
			
			// aapt resource value: 0x7f0a006d
			public const int layoutCardExpiration = 2131361901;
			
			// aapt resource value: 0x7f0a0060
			public const int layoutCreditCardMenu = 2131361888;
			
			// aapt resource value: 0x7f0a0069
			public const int layoutCreditCardSignUp = 2131361897;
			
			// aapt resource value: 0x7f0a005c
			public const int layoutEmailMenu = 2131361884;
			
			// aapt resource value: 0x7f0a0049
			public const int layoutMenu = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int layoutOrderSection = 2131361866;
			
			// aapt resource value: 0x7f0a005a
			public const int layoutPhoneMenu = 2131361882;
			
			// aapt resource value: 0x7f0a0054
			public const int layoutProfilePicture = 2131361876;
			
			// aapt resource value: 0x7f0a004c
			public const int layoutProfileSection = 2131361868;
			
			// aapt resource value: 0x7f0a005e
			public const int layoutPurchasesMenu = 2131361886;
			
			// aapt resource value: 0x7f0a0048
			public const int layoutSignIn = 2131361864;
			
			// aapt resource value: 0x7f0a000a
			public const int left = 2131361802;
			
			// aapt resource value: 0x7f0a000c
			public const int linearLayout1 = 2131361804;
			
			// aapt resource value: 0x7f0a000f
			public const int linearLayout2 = 2131361807;
			
			// aapt resource value: 0x7f0a0012
			public const int linearLayout3 = 2131361810;
			
			// aapt resource value: 0x7f0a0015
			public const int linearLayout4 = 2131361813;
			
			// aapt resource value: 0x7f0a0018
			public const int linearLayout5 = 2131361816;
			
			// aapt resource value: 0x7f0a0040
			public const int linearLayoutItemInfo = 2131361856;
			
			// aapt resource value: 0x7f0a004d
			public const int menu_section_items_container = 2131361869;
			
			// aapt resource value: 0x7f0a0001
			public const int normal = 2131361793;
			
			// aapt resource value: 0x7f0a002a
			public const int picker_subtitle = 2131361834;
			
			// aapt resource value: 0x7f0a004e
			public const int recyclerViewMenu = 2131361870;
			
			// aapt resource value: 0x7f0a004b
			public const int recyclerViewOrderSection = 2131361867;
			
			// aapt resource value: 0x7f0a0053
			public const int recyclerViewOrderSection2 = 2131361875;
			
			// aapt resource value: 0x7f0a000b
			public const int right = 2131361803;
			
			// aapt resource value: 0x7f0a0002
			public const int small = 2131361794;
			
			// aapt resource value: 0x7f0a006b
			public const int spinnerCardType = 2131361899;
			
			// aapt resource value: 0x7f0a0005
			public const int standard = 2131361797;
			
			// aapt resource value: 0x7f0a0010
			public const int tabEvents = 2131361808;
			
			// aapt resource value: 0x7f0a0019
			public const int tabInfos = 2131361817;
			
			// aapt resource value: 0x7f0a000d
			public const int tabMenu = 2131361805;
			
			// aapt resource value: 0x7f0a0013
			public const int tabOrder = 2131361811;
			
			// aapt resource value: 0x7f0a0016
			public const int tabProfile = 2131361814;
			
			// aapt resource value: 0x7f0a0056
			public const int textView1 = 2131361878;
			
			// aapt resource value: 0x7f0a0063
			public const int textView2 = 2131361891;
			
			// aapt resource value: 0x7f0a0008
			public const int top = 2131361800;
			
			// aapt resource value: 0x7f0a006f
			public const int txtCardHolder = 2131361903;
			
			// aapt resource value: 0x7f0a0073
			public const int txtConfirm = 2131361907;
			
			// aapt resource value: 0x7f0a006c
			public const int txtCreditCardNumber = 2131361900;
			
			// aapt resource value: 0x7f0a003c
			public const int txtEmail = 2131361852;
			
			// aapt resource value: 0x7f0a0011
			public const int txtEvents = 2131361809;
			
			// aapt resource value: 0x7f0a003b
			public const int txtFirstName = 2131361851;
			
			// aapt resource value: 0x7f0a0071
			public const int txtFullName = 2131361905;
			
			// aapt resource value: 0x7f0a001a
			public const int txtInfos = 2131361818;
			
			// aapt resource value: 0x7f0a000e
			public const int txtMenu = 2131361806;
			
			// aapt resource value: 0x7f0a0041
			public const int txtName = 2131361857;
			
			// aapt resource value: 0x7f0a0014
			public const int txtOrder = 2131361812;
			
			// aapt resource value: 0x7f0a0037
			public const int txtOrderDetails = 2131361847;
			
			// aapt resource value: 0x7f0a0036
			public const int txtOrderQuestion = 2131361846;
			
			// aapt resource value: 0x7f0a0038
			public const int txtPassword = 2131361848;
			
			// aapt resource value: 0x7f0a0072
			public const int txtPhoneNumber = 2131361906;
			
			// aapt resource value: 0x7f0a0042
			public const int txtPrice = 2131361858;
			
			// aapt resource value: 0x7f0a0017
			public const int txtProfile = 2131361815;
			
			// aapt resource value: 0x7f0a0067
			public const int txtSignUp = 2131361895;
			
			// aapt resource value: 0x7f0a0045
			public const int txtTime = 2131361861;
			
			// aapt resource value: 0x7f0a006a
			public const int txtViewCardType = 2131361898;
			
			// aapt resource value: 0x7f0a006e
			public const int txtViewExpiration = 2131361902;
			
			// aapt resource value: 0x7f0a0068
			public const int txtViewPaymentInfo = 2131361896;
			
			// aapt resource value: 0x7f0a0047
			public const int viewFlipper = 2131361863;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_friendpickerfragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_login_activity_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_picker_activity_circle_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_picker_checkbox = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_image = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_list_row = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_list_section_header = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_search_box = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_title_bar = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_picker_title_bar_stub = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_placepickerfragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_placepickerfragment_list_row = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_search_bar_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_tooltip_bubble = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int com_facebook_usersettingsfragment = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_ordernow_confirm = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_sign_up = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int item_card = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int item_card_test = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int item_row = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Main = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int menu_section_items = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int menu_sections = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int order_card = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int order_card_test = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int order_section = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int profile_section = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int sign_in = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int sign_up_credit = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int sign_up_user = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080020
			public const int app_id = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int app_name = 2131230750;
			
			// aapt resource value: 0x7f080023
			public const int card_type_prompt = 2131230755;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_choose_friends = 2131230737;
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_dialogloginactivity_ok_button = 2131230720;
			
			// aapt resource value: 0x7f08001c
			public const int com_facebook_image_download_unknown_error = 2131230748;
			
			// aapt resource value: 0x7f080015
			public const int com_facebook_internet_permission_error_message = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int com_facebook_internet_permission_error_title = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int com_facebook_like_button_liked = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_like_button_not_liked = 2131230721;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_loading = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int com_facebook_loginview_cancel_action = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int com_facebook_loginview_log_in_button = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int com_facebook_loginview_log_out_action = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int com_facebook_loginview_log_out_button = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int com_facebook_loginview_logged_in_as = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int com_facebook_loginview_logged_in_using_facebook = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int com_facebook_logo_content_description = 2131230729;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_nearby = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_picker_done_button_text = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int com_facebook_placepicker_subtitle_format = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131230735;
			
			// aapt resource value: 0x7f080018
			public const int com_facebook_requesterror_password_changed = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int com_facebook_requesterror_permissions = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int com_facebook_requesterror_reconnect = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int com_facebook_requesterror_relogin = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int com_facebook_requesterror_web_login = 2131230742;
			
			// aapt resource value: 0x7f08001b
			public const int com_facebook_tooltip_default = 2131230747;
			
			// aapt resource value: 0x7f08000a
			public const int com_facebook_usersettingsfragment_log_in_button = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int com_facebook_usersettingsfragment_logged_in = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131230732;
			
			// aapt resource value: 0x7f08001f
			public const int get_started = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int hello = 2131230749;
			
			// aapt resource value: 0x7f080021
			public const int sign_up = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int sign_up_pressed = 2131230754;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int CardView_Dark = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Light = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int CustomActionBarTheme = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MyActionBar = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int SplashTheme = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_loginview_default_style = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_silver_style = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int dialog_animation = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int tooltip_bubble_text = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771986};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 3
			public const int com_facebook_like_view_auxiliary_view_position = 3;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_foreground_color = 0;
			
			// aapt resource value: 4
			public const int com_facebook_like_view_horizontal_alignment = 4;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_style = 2;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771995,
					2130771996};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
